# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import coordination_pb2 as coordination__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coordination_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinationStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/limen.distributed.Coordination/Register',
                request_serializer=coordination__pb2.NodeInfo.SerializeToString,
                response_deserializer=coordination__pb2.RegisterAck.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/limen.distributed.Coordination/Heartbeat',
                request_serializer=coordination__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=coordination__pb2.HeartbeatAck.FromString,
                _registered_method=True)
        self.SyncCalibration = channel.unary_unary(
                '/limen.distributed.Coordination/SyncCalibration',
                request_serializer=coordination__pb2.SyncCalibrationRequest.SerializeToString,
                response_deserializer=coordination__pb2.HardwareDeltaModelProto.FromString,
                _registered_method=True)
        self.ListPeers = channel.unary_unary(
                '/limen.distributed.Coordination/ListPeers',
                request_serializer=coordination__pb2.Empty.SerializeToString,
                response_deserializer=coordination__pb2.NodeList.FromString,
                _registered_method=True)
        self.CompilePartition = channel.unary_unary(
                '/limen.distributed.Coordination/CompilePartition',
                request_serializer=coordination__pb2.CompilePartitionRequest.SerializeToString,
                response_deserializer=coordination__pb2.CompilePartitionResult.FromString,
                _registered_method=True)
        self.TransportFeedforward = channel.unary_unary(
                '/limen.distributed.Coordination/TransportFeedforward',
                request_serializer=coordination__pb2.FeedforwardRequest.SerializeToString,
                response_deserializer=coordination__pb2.FeedforwardResponse.FromString,
                _registered_method=True)


class CoordinationServicer:
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncCalibration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompilePartition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransportFeedforward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=coordination__pb2.NodeInfo.FromString,
                    response_serializer=coordination__pb2.RegisterAck.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=coordination__pb2.HeartbeatRequest.FromString,
                    response_serializer=coordination__pb2.HeartbeatAck.SerializeToString,
            ),
            'SyncCalibration': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncCalibration,
                    request_deserializer=coordination__pb2.SyncCalibrationRequest.FromString,
                    response_serializer=coordination__pb2.HardwareDeltaModelProto.SerializeToString,
            ),
            'ListPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPeers,
                    request_deserializer=coordination__pb2.Empty.FromString,
                    response_serializer=coordination__pb2.NodeList.SerializeToString,
            ),
            'CompilePartition': grpc.unary_unary_rpc_method_handler(
                    servicer.CompilePartition,
                    request_deserializer=coordination__pb2.CompilePartitionRequest.FromString,
                    response_serializer=coordination__pb2.CompilePartitionResult.SerializeToString,
            ),
            'TransportFeedforward': grpc.unary_unary_rpc_method_handler(
                    servicer.TransportFeedforward,
                    request_deserializer=coordination__pb2.FeedforwardRequest.FromString,
                    response_serializer=coordination__pb2.FeedforwardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'limen.distributed.Coordination', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('limen.distributed.Coordination', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coordination:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/limen.distributed.Coordination/Register',
            coordination__pb2.NodeInfo.SerializeToString,
            coordination__pb2.RegisterAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/limen.distributed.Coordination/Heartbeat',
            coordination__pb2.HeartbeatRequest.SerializeToString,
            coordination__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncCalibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/limen.distributed.Coordination/SyncCalibration',
            coordination__pb2.SyncCalibrationRequest.SerializeToString,
            coordination__pb2.HardwareDeltaModelProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/limen.distributed.Coordination/ListPeers',
            coordination__pb2.Empty.SerializeToString,
            coordination__pb2.NodeList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompilePartition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/limen.distributed.Coordination/CompilePartition',
            coordination__pb2.CompilePartitionRequest.SerializeToString,
            coordination__pb2.CompilePartitionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransportFeedforward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/limen.distributed.Coordination/TransportFeedforward',
            coordination__pb2.FeedforwardRequest.SerializeToString,
            coordination__pb2.FeedforwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
